### ISSUE TITLE
Rôle ROLE_USER

### ISSUE THREAD

**Issue by Dylio** [thebigandrew/rdvenligne#16]
Le rôle ROLE_USER n'est pas correctement inscrit dans la base de données quand l'utilisateur s'inscrit
![capture](https://user-images.githubusercontent.com/16857799/40916957-f26db7ee-6801-11e8-92ac-892681cf5b60.PNG)
.

**Comment by thebigandrew** [comment]
FIX : j'ai créé le rôle ROLE_CLIENT et récupéré toutes les mentions de ROLE_USER dans le code source. Le problème venait du fait que FOS par défaut ne sauvegarde aucune mention du ROLE_USER en base de données.
