### ISSUE TITLE
Dépassement page table

### ISSUE THREAD

**Issue by Dylio** [thebigandrew/rdvenligne#17]
Dépassement des tables sur l'interface (=>redimensionnement des tables)
![capture](https://user-images.githubusercontent.com/16857799/40921831-e1a0631c-6810-11e8-9080-ef05287a8d2e.PNG)

**Comment by thebigandrew** [comment]
Corrigé en incluant le fichier CSS bootstrap dans le <head> des pages utilisant datatables
